spring.application.name=PasswordVault

spring.datasource.url=jdbc:postgresql://localhost:5432/password_vault
spring.datasource.username=postgres
spring.datasource.password=mani

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8082



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=manikanta28082005@gmail.com
spring.mail.password=smvf xcfl dmsv ergc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true